"""Initial migration

Revision ID: 320e0de68928
Revises: 
Create Date: 2024-03-09 23:06:42.945735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320e0de68928'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('start_data', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remind_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=100), nullable=True),
    sa.Column('file_url', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['remind_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('cases')
    op.drop_table('users')
    # ### end Alembic commands ###
