"""type -> repeat

Revision ID: 7ecec707e2ac
Revises: f2f3e7762c5b
Create Date: 2024-03-17 18:26:50.392181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ecec707e2ac'
down_revision: Union[str, None] = 'f2f3e7762c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('repeat', sa.String(length=100), nullable=True))
    op.drop_column('cases', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('cases', 'repeat')
    # ### end Alembic commands ###
