"""fix start_date(cases)

Revision ID: 8753f133f606
Revises: 320e0de68928
Create Date: 2024-03-17 15:51:09.112173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8753f133f606'
down_revision: Union[str, None] = '320e0de68928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('start_date', sa.Date(), nullable=False))
    op.drop_column('cases', 'start_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('start_data', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('cases', 'start_date')
    # ### end Alembic commands ###
