"""add is_finished

Revision ID: 90c21167b9fc
Revises: 7ecec707e2ac
Create Date: 2024-03-17 21:12:25.204373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c21167b9fc'
down_revision: Union[str, None] = '7ecec707e2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('is_finished', sa.Boolean(), nullable=True))
    op.add_column('file', sa.Column('case_id', sa.Integer(), nullable=True))
    op.drop_constraint('file_remind_id_fkey', 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'cases', ['case_id'], ['id'])
    op.drop_column('file', 'remind_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('remind_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key('file_remind_id_fkey', 'file', 'cases', ['remind_id'], ['id'])
    op.drop_column('file', 'case_id')
    op.drop_column('cases', 'is_finished')
    # ### end Alembic commands ###
