"""delete finish_date

Revision ID: f2f3e7762c5b
Revises: 8753f133f606
Create Date: 2024-03-17 16:41:48.586624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f3e7762c5b'
down_revision: Union[str, None] = '8753f133f606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'finish_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('finish_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
